config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :folders do
    resources :questions
  end

  devise_for :users

end

app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  state_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class City < ActiveRecord::Base
  belongs_to :state
end

app/models/collection.rb
# == Schema Information
#
# Table name: collections
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Collection < ActiveRecord::Base
  belongs_to :user
end

app/models/country.rb
# == Schema Information
#
# Table name: countries
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Country < ActiveRecord::Base
end

app/models/folder.rb
# == Schema Information
#
# Table name: folders
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  parent_folder_id :integer
#  user_id          :integer
#  created_at       :datetime
#  updated_at       :datetime
#

class Folder < ActiveRecord::Base
  belongs_to :parent_folder, class: 'Folder'
  belongs_to :user
  has_many :questions
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id            :integer          not null, primary key
#  name          :string(255)
#  question_text :text
#  type_id       :integer
#  folder_id     :integer
#  user_id       :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class Question < ActiveRecord::Base
  belongs_to :type, class: 'QuestionType'
  belongs_to :folder
  belongs_to :user
end

app/models/question_collection.rb
# == Schema Information
#
# Table name: question_collections
#
#  id            :integer          not null, primary key
#  collection_id :integer
#  question_id   :integer
#  sort_num      :integer
#  visible       :boolean
#  created_at    :datetime
#  updated_at    :datetime
#

class QuestionCollection < ActiveRecord::Base
  belongs_to :collection
  belongs_to :question
end

app/models/question_type.rb
# == Schema Information
#
# Table name: question_types
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  locale     :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class QuestionType < ActiveRecord::Base
end

app/models/state.rb
# == Schema Information
#
# Table name: states
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  country_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class State < ActiveRecord::Base
  belongs_to :country
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :folders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController

  before_action :authenticate_user!
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  def index
    @folders = current_user.folders
  end

  def show
  end

  def new
    @folder = Folder.new
  end

  def create
    @folder = Folder.new(folder_params)
    @folder.user = current_user
    if @folder.save
      redirect_to folders_path
    else
      render new_folder_path
    end
  end

  def edit
  end

  def update
    @folder = Folder.find(params[:id])
    if @folder.update(folder_params)
      redirect_to folders_path
    else
      render edit_folder_path(@folder)
    end
  end

  def destroy
  end

  private

    def set_record
      @folder = Folder.find(params[:id])
    end

    def folder_params
      params.require(:folder).permit(:name, :parent_folder_id, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_record, only: [:show, :edit, :update, :destroy]
  before_action :fill_tables, only: [:new, :edit]

  def index
  end

  def show
  end

  def new
    @question = Question.new
    folder = Folder.find(params[:folder_id])
    @question.folder = folder
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to edit_folder_path(@question.folder)
    else
      render new_question_path
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

    def set_record
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:name, :folder_id, :user_id)
    end

    def fill_tables
      @types = QuestionType.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/folders/_form.html.erb
<%= simple_form_for @folder do |f| %>

  <%= f.input :name %>
  <%= f.button :submit %>

<% end %>

app/views/folders/_questions.html.erb
<h3><%= t('.questions_title') %></h3>

<p>
  <%= link_to t('.add_question'), new_folder_question_path(@folder) %>
</p>

<table>
  <thead>
    <tr>
      <th><%=t ('.name_column') %></th>
      <th><%=t ('.type_column') %></th>
      <th><%=t ('.actions_column') %></th>
    </tr>
  </thead>
  <tbody>
    <% @folder.questions.each do |question| %>
    <tr>
      <td>
        <%= question.name %>
      </td>
      <td>
        <%= question.type.name unless question.type.nil? %>
      </td>
      <td>
        <%= link_to t('.edit_question'), edit_folder_question_path(question.folder, question) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/folders/create.html.erb
<h1>Folders#create</h1>
<p>Find me in app/views/folders/create.html.erb</p>

app/views/folders/destroy.html.erb
<h1>Folders#destroy</h1>
<p>Find me in app/views/folders/destroy.html.erb</p>

app/views/folders/edit.html.erb
<h1><%=t '.title' %></h1>

<p>
  <%= link_to t('.return_index'), folders_path %>
</p>

<%= form_for @folder do |f| %>
  <%= render 'form' %>
<% end %>

<%= render 'questions' %>

app/views/folders/index.html.erb
<h1><%=t '.title' %></h1>

<p>
  <a href="<%= url_for controller: 'folders', action: 'new' %>"><%=t '.new_folder' %></a>
</p>

<table>
  <thead>
    <tr>
      <th><%=t '.column_name' %></th>
      <th><%=t '.column_count_questions' %></th>
      <th><%=t '.column_actions' %></th>
    </tr>
  </thead>
  <tbody>
    <% @folders.each do |folder| %>
    <tr>
      <td>
        <%= folder.name %>
      </td>
      <td>
        <%= folder.questions.size %>
      </td>
      <td>
        <%= link_to t('.edit_folder'), edit_folder_path(folder) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/folders/new.html.erb
<h1><%=t '.title' %></h1>

<p>
  <%= link_to t('.return_index'), folders_path %>
</p>

<%= form_for @folder do |f| %>
  <%= render 'form' %>
<% end %>

app/views/folders/show.html.erb
<h1>Folders#show</h1>
<p>Find me in app/views/folders/show.html.erb</p>

app/views/folders/update.html.erb
<h1>Folders#update</h1>
<p>Find me in app/views/folders/update.html.erb</p>

app/views/home/index.html.erb
<h1>Index</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Viztapmx</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<ul>
  <li>
    <%= link_to t('folders_link'), folders_path %>
  </li>
</ul>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for [@question.folder, @question] do |f| %>

  <div>
    <%= f.hidden_field :folder_id %>
  </div>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :type %>
    <%= f.collection_select :type_id, @types, :id, :name, prompt: true %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/edit.html.erb
<h1><%=t ('.edit_question_title') %></h1>

<p>
  <%= link_to t('.return_list'), edit_folder_path(@question.folder) %>
</p>

<%= render 'form' %>

app/views/questions/index.html.erb
<h1>Questions#index</h1>
<p>Find me in app/views/questions/index.html.erb</p>

app/views/questions/new.html.erb
<h1><%= t('.question_title') %></h1>

<p>
  <%= link_to t('.return_list'), edit_folder_path(@question.folder.id) %>
</p>

<%= render 'form' %>

app/views/questions/show.html.erb
<h1>Questions#show</h1>
<p>Find me in app/views/questions/show.html.erb</p>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>